### ISSUE TITLE
Documentation is not complete

### ISSUE THREAD

**Issue by aromalanil** [aromalanil/useCustomHooks#27]
## What is the Problem?
The documentation for the hooks are not complete. Only `useLocalStorage` hook has complete documentation. Other hooks does not contain **Parameters** and **Return** values in their documentation

## Possible Solution
Add parameters and return values to the docs of all other hooks

## What to contribute? How can you help?

- The code for each hook contains corresponding parameters and return values, defined as JSdoc comments. 
- You can take the data from there and add it to the documentation

**Comment by Abhishekchauhan089** [comment]
yes. i would like to work on this project.

**Comment by aromalanil** [comment]
@Abhishekchauhan089 You can work on it now 🙂

**Comment by Abhishekchauhan089** [comment]
@aromalanil ya, i'm working. and get the work done soon
